name: Bot 1

on:
  workflow_dispatch:
  schedule:
    # Runs every 5 hours and 40 minutes (UTC times)
    - cron: '0 0 * * *'
    - cron: '40 5 * * *'
    - cron: '20 11 * * *'
    - cron: '0 17 * * *'
    - cron: '40 22 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - id: 1
            game_id_secret: GAME_ID_28
            game_password_secret: GAME_PASSWORD_28

          - id: 2
            game_id_secret: GAME_ID_25
            game_password_secret: GAME_PASSWORD_25

          - id: 3
            game_id_secret: GAME_ID_8
            game_password_secret: GAME_PASSWORD_8

          - id: 4
            game_id_secret: GAME_ID_19
            game_password_secret: GAME_PASSWORD_19

          - id: 5
            game_id_secret: GAME_ID_14
            game_password_secret: GAME_PASSWORD_14

          - id: 6
            game_id_secret: GAME_ID_30
            game_password_secret: GAME_PASSWORD_30

          - id: 7
            game_id_secret: GAME_ID_34
            game_password_secret: GAME_PASSWORD_34

          - id: 8
            game_id_secret: GAME_ID_20
            game_password_secret: GAME_PASSWORD_20

          - id: 9
            game_id_secret: GAME_ID_3
            game_password_secret: GAME_PASSWORD_3

          - id: 10
            game_id_secret: GAME_ID_39
            game_password_secret: GAME_PASSWORD_39

          - id: 11
            game_id_secret: GAME_ID_37
            game_password_secret: GAME_PASSWORD_37

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Bot
        run: mvn -q clean compile exec:java -Dexec.mainClass="Main"
        env:
          GAME_ID: ${{ secrets[matrix.game_id_secret] }}
          GAME_PASSWORD: ${{ secrets[matrix.game_password_secret] }}
